### ISSUE TITLE
Code Review (checklist)

### ISSUE THREAD

**Issue by raijinmaruh** [raijinmaruh/pequenos_projetos#1]
### **Projeto: ["Contadinho"](https://github.com/raijinmaruh/pequenos_projetos/tree/master/contadinho)**

* Reportado: 11:05 AM
* Utilizado o Habitica
* Branch: features

1. Pastas
- [x] Organizar melhor as pastas
- [ ] Implementar uma arquitetura
2. CSS
- [x] Incluir figuras de social media - [Boxicons](https://boxicons.com/)
- [x] Incluir figura principal - [Boxicons](https://boxicons.com/)
- [x] Refazer botão de calculo 
- [x] Refazer campo
- [x] Trocar cor das letras?
- [x] Diminuir letras da saída de dados
- [x] Escolher outro esquema de cores
- [x] Metatag para favicon
- [x] Consertar botões social media
3. Javacript
- [x] Adquirir o valor do input
- [x] Fazer função para calcular
- [ ] Armazenar últimas consultas no localStorage
